export const JOB_TITLES = [
  "AI Agentic Engineer",
  "AI Applied Engineer",
  "Senior Software Engineer",
  "Forward Deployed Engineer",
  "AI Senior Software Engineer",
  "AI Forward Deployed Engineer",
  "AI Mid-Level Engineer",
  "AI Software Engineer",
  "Design Engineer",
  "AI Front End Engineer",
  "AI Back End Engineer",
  "AI Architecture Engineer",
  "AI Architect Engineer",
  "AI Onboarding Engineer",
  "AI Full Stack Engineer",
  "AI Orchestration Engineer",
  "GTM Engineer",
  "AI Research Engineer",
  "ML Infrastructure Engineer",
  "AI Platform Engineer",
] as const;
